#!/usr/bin/env python
# -*- coding: utf-8 -*-
lang_cn_s = {
    "Fanseline Audio Visualizer": "帆室邻音频可视化视频制作工具",
    "Stop Blending": "取消渲染",
    "(Running)": "（渲染中）",
    "Blend & Export": "渲染输出",
    "Foreground Selected: ": "已选择主图片： ",
    "Background Selected: ": "已选择背景图片： ",
    "Logo Selected: ": "已选择图标： ",
    "Audio Selected: ": "已选择音频： ",
    "Image files": "图片文件",
    "All files": "全部文件",
    "Audio files": "音频文件",
    "Video files": "视频文件",
    "Font files": "字体文件",
    "_Visualize": "_音频可视化",
    "Output Path Selected: ": "已选择输出路径： ",
    "Font Selected: ": "已选择字体： ",
    "Cannot Blend": "无法开始渲染",
    "Save Image as...": "图片另存为……",
    "Snap": "快照",
    "Cannot Save Image!": "无法储存图片！",

    "Please select the correct audio file!": "请先正确选择音频文件！",
    "Please select the correct output path!": "请正确选择输出路径！",
    "Please input the corrent file name!": "请正确输入输出文件名！",
    "Stop Blending...": "正在取消渲染……",

    "Audio (REQUIRED)": "声音文件【必选】",
    "Output (REQUIRED)": "输出路径【必选】",
    "Foreground Image": "选择主图片",
    "Background Image": "选择背景图片",
    "Logo File": "选择小图标",
    "Your Text:": "请输入文字：",
    "Font Size:": "字体大小：",
    "Text Brt.:": "文字亮度：",
    "Font File": "选择字体文件",
    "Video Size:": "设置视频尺寸：",
    "FPS:": "视频帧率：",
    "Video BR (Mbps):": "视频码率(Mbps)：",
    "Auto Bit Rate": "自动视频码率",
    "Analyze Freq:": "频率分析范围：",
    "to": "至",
    "Hz": "赫兹",
    "Spectrum Num:": "频谱条的数量：",
    "Spectrum Scalar:": "频谱条灵敏倍率：",
    "Spec. Brt.:": "频谱亮度：",
    "Spec. Sat.:": "频谱饱和度：",
    "Spectrum Stabilize:": "频谱条防抖：",
    "Spec. Hue:": "频谱色调：",

    "Rainbow 4x": "彩虹 4x",
    "Rainbow 2x": "彩虹 2x",
    "Rainbow 1x": "彩虹 1x",
    "White": "白色",
    "Black": "黑色",
    "Gray": "灰色",
    "Red": "红色",
    "Green": "绿色",
    "Blue": "蓝色",
    "Yellow": "黄色",
    "Magenta": "品红",
    "Purple": "紫色",
    "Cyan": "青色",
    "Light Green": "浅绿",
    "Green - Blue": "渐变：蓝-绿",
    "Magenta - Purple": "渐变：红-紫",
    "Red - Yellow": "渐变：红-黄",
    "Yellow - Green": "渐变：黄-绿",
    "Blue - Purple": "渐变：蓝-紫",

    "Audio BR:": "设置音频码率：",
    "Normalize Volume": "标准化音量",
    "Audio Preset:": "音频预设：",
    "Music-HQ": "音乐-高品质",
    "Music-MQ": "音乐-中品质",
    "Music-LQ": "音乐-低品质",
    "Voice-HQ": "语音-高品质",
    "Voice-MQ": "语音-中品质",
    "Voice-LQ": "语音-低品质",

    "Video Preset:": "视频预设：",
    "Square": "方形",
    "Landscape": "横屏",
    "Portrait": "竖屏",
    "(Slow)": "(缓慢)",
    "Preview": "预览",
    "Welcome to use": "欢迎使用",
    "-Please Select-": "-请选择-",
    "Notice": "通知",
    "Please stop blending before quit!": "请在退出前取消渲染！",
    "Are you sure to overwrite this file?": "确定覆盖文件吗？",
    "Are you sure to stop blending?": "确定取消渲染吗？",

    "Spectrum Style:": "频谱风格：",
    "Solid Line": "实线频谱",
    "Dot Line": "点阵频谱",
    "Single Dot": "单点频谱",
    "Double Dot": "双点频谱",
    "Concentric": "同心圆",
    "Line Graph": "折线图",
    "Classic 1": "经典1",
    "Classic 2": "经典2",
    "Classic 3": "经典3",
    "Classic 4": "经典4",
    "Classic Dot 1": "经典点阵",
    "Classic Dot 2": "经典点阵2",
    "Classic Dot 3": "经典点阵3",
    "Classic Dot 4": "经典点阵4",
    "Stem Plot 1": "Stem图1",
    "Stem Plot 2": "Stem图2",
    "Stem Plot 3": "Stem图3",
    "Stem Plot 4": "Stem图4",
    "No Spectrum": "无频谱",
    "Line Width:": "频谱线宽：",
    "BG Mode:": "背景模式：",
    "Blurred BG Image": "模糊背景",
    "Normal BG Image": "正常背景",
    "Blurred BG Only": "仅模糊背景",
    "Normal BG Only": "仅正常背景",
    "Transparent": "透明背景",
    "Spectrum Only": "仅频谱",
    "Glow Text": "发光文字",
    "Glow Spec. (SLOW)": "发光频谱【缓慢】",
    "Project Website: ": "项目网站：",
    "Spin FG(rpm):": "旋转主图(转/分)：",
    "Error! Cannot save config!": "错误！不能保存配置！",
    "FFMPEG not found, please install FFMPEG!": "FFMPEG未安装，请安装FFMPEG！",

}

lang_keys = list(lang_cn_s.keys())
lang_en = {}
for lang_key in lang_keys:
    lang_en[lang_key] = lang_key
