lang_cn_s = {
    "Fanseline Audio Visualizer": "帆室邻音频可视化视频制作工具",
    "Stop Blending": "取消渲染",
    "(Running)": "（渲染中）",
    "Blend & Export": "渲染输出",
    "Image Selected: ": "已选择图片： ",
    "Logo Selected: ": "已选择图标： ",
    "Audio Selected: ": "已选择音频： ",
    "Image files": "图片文件",
    "All files": "全部文件",
    "Audio files": "音频文件",
    "Font files": "字体文件",
    "_Visualize": "_音频可视化",
    "Output Path Selected: ": "已选择输出路径： ",
    "Font Selected: ": "已选择字体： ",
    "Cannot Blend": "无法开始渲染",

    "Please select the correct audio file!": "请先正确选择音频文件！",
    "Please select the correct output path!": "请正确选择输出路径！",
    "Please input the corrent file name!": "请正确输入输出文件名！",
    "Stop Blending...": "正在取消渲染……",

    "Audio File(REQUIRED)": "选择声音文件【必选】",
    "Output Path(REQUIRED)": "选择输出路径【必选】",
    "FG & BG Image": "选择主图片",
    "Logo File": "选择小图标",
    "Your Text Here:": "请输入文字：",
    "Font File:": "字体文件：",
    "Select Font File": "选择字体文件",
    "Video Size:": "设置视频尺寸：",
    "Video FPS:": "设置视频帧率：",
    "Video BR (Mbps):": "设置视频码率(Mbps)：",
    "Auto Bit Rate": "自动计算视频码率",
    "Analyze Freq:": "频率分析范围：",
    "to": "至",
    "Hz": "赫兹",
    "Spectrum Num:": "频谱条的数量：",
    "Spectrum Scalar:": "频谱条灵敏倍率：",
    "Spectrum Color:": "频谱条颜色：",

    "Rainbow 4x": "彩虹 4x",
    "Rainbow 2x": "彩虹 2x",
    "Rainbow 1x": "彩虹 1x",
    "White": "白色",
    "Red": "红色",
    "Green": "绿色",
    "Blue": "蓝色",
    "Yellow": "黄色",
    "Magenta": "品红",
    "Purple": "紫色",
    "Cyan": "青色",
    "Light Green": "浅绿",
    "Gradient: Green - Blue": "渐变：蓝-绿",
    "Gradient: Magenta - Purple": "渐变：红-紫",
    "Gradient: Red - Yellow": "渐变：红-黄",
    "Gradient: Yellow - Green": "渐变：黄-绿",
    "Gradient: Blue - Purple": "渐变：蓝-紫",

    "Audio BR:": "设置音频码率：",
    "Normalize Volume": "标准化音量",
    "Audio Preset:": "音频预设：",
    "Music-HQ": "音乐-高品质",
    "Music-MQ": "音乐-中品质",
    "Music-LQ": "音乐-低品质",
    "Voice-HQ": "语音-高品质",
    "Voice-MQ": "语音-中品质",
    "Voice-LQ": "语音-低品质",

    "Video Preset:": "视频预设：",
    "Square": "方形",
    "Portrait": "竖屏",
    "(Slow)": "(缓慢)",
    "Preview": "预览",
    "Welcome to use": "欢迎使用",
}

lang_keys = list(lang_cn_s.keys())
lang_en = {}
for lang_key in lang_keys:
    lang_en[lang_key] = lang_key
