#!/usr/bin/env python
# -*- coding: utf-8 -*-

lang_cn_s = {
    "Fanseline Visualizer": "Fanseline Visualizer",
    "Stop Rendering": "取消渲染",
    "(Rendering...)": "(渲染中……)",
    "(Computing...)": "(计算中……)",
    "ON": "开",
    "OFF": "关",
    "Render & Export": "渲染输出",
    "Open": "打开",
    "Use Color": "使用纯色",
    "No Image File": "没有图片文件",
    "Frequency Analyzer Preset": "频率分析预设",
    "Audio": "音频",
    "Video": "视频",
    "Spectrum": "频谱",
    "Render": "渲染",
    "<FFT Lower>": "FFT低频",
    "<FFT Upper>": "FFT高频",
    "Analyzer Frequency Range (Hz)": "频率分析器范围(赫兹)",
    "Analyzer Range:": "分析器范围：",

    "<Please open an audio file>": "<请打开一个音频文件>",
    "<Please open a font file>": "<请打开一个字体文件>",
    "Select Font": "选择字体",
    "Open Audio File": "打开音频文件",
    "Audio Settings": "音频设置",
    "Video Settings": "视频设置",
    "Video Preset": "视频预设",
    "Auto Video Bit Rate": "自动视频码率",
    "Frame Rate (FPS)": "帧率(FPS)",
    "<FPS>": "<帧率>",
    "Frame Size": "帧大小",
    "<Width>": "<宽>",
    "<Height>": "<高>",
    "Video Bit Rate (Mbps)": "视频码率 (Mbps)",
    "<Bit Rate>": "<码率>",
    "Audio Bit Rate": "音频码率",
    "Volume Normalize": "音量标准化",
    "Volume Normalize:": "音量标准化：",
    "Remove": "移除",
    "Foreground": "主图片",
    "Background": "背景图片",
    "Logo": "小图标",
    "Select Audio": "选择音频",
    "Select Images": "选择图片",
    "Back to Main Menu": "返回主菜单",
    "Select an Image": "选择一张图片",
    "Select Audio File": "选择音频文件",
    "Select Color": "选择颜色",
    "Customize Color": "自定义颜色",
    "Foreground Selected: ": "已选择主图片： ",
    "Background Selected: ": "已选择背景图片： ",
    "Logo Selected: ": "已选择图标： ",
    "Audio Selected: ": "已选择音频： ",
    "Image Files": "图片文件",
    "All Files": "全部文件",
    "Audio Files": "音频文件",
    "Video Files": "视频文件",
    "Font Files": "字体文件",
    "Font Size": "文字大小",
    "Text Settings": "文字设置",
    "Edit Text": "编辑文字",
    "Clear Text": "清空文本",
    "Refresh Preview": "刷新预览",
    "<Your text here>": "<在此输入文字>",
    "Use File Name": "使用文件名",
    "Select Font File": "选择字体文件",
    "Image Settings": "图片设置",
    "Background Mode": "背景模式",
    "Spin Foreground": "旋转主图",
    "No Spin": "不旋转",
    "Clockwise": "顺时针旋转",
    "Counterclockwise": "逆时针旋转",
    "Spin Speed (rpm)": "旋转速度 (转/分钟)",
    "<Spin Speed>": "<旋转速度>",
    "Customize": "自定义",
    "Spectrum Color": "频谱颜色",
    "Spectrum Saturation": "频谱饱和度",
    "Spectrum Brightness": "频谱亮度",
    "Glow Effect (Slow)": "发光效果 (缓慢)",

    "Spectrum Style": "频谱样式",
    "Spectrum Number": "频谱数量",
    "Spectrum Thickness": "频谱线宽",
    "Spectrum Scalar": "频谱条灵敏倍率",
    "Spectrum Stabilize": "频谱防抖",

    "Save Project": "保存项目",
    "Load Project": "读取项目",
    "Save Project as...": "项目保存为……",
    "FV Project Files": "FV项目文件",
    "Open Project File...": "打开项目文件……",
    "File Error": "文件错误",
    "Cannot Read this Project!": "无法读取该项目！",

    "Save as PNG": "保存为PNG",
    "Save as JPG": "保存为JPG",
    "Save as BMP": "保存为BMP",
    "PNG Files": "PNG文件",
    "JPG Files": "JPG文件",
    "BMP Files": "BMP文件",
    "Files": "文件",
    "Output Config": "输出配置",
    "Rendering:": "渲染中：",
    "Compositing Audio...": "音频合成中……",
    "Analyzing Audio...": "分析音频中……",
    "Mission Complete!": "任务完成！",
    "Elapsed Time:": "已用时：",
    "Remaining Time:": "剩余时间：",

    "Output Path:": "输出路径：",
    "Audio Path:": "音频路径：",
    "Audio Settings:": "音频设置：",
    "Video Settings:": "视频设置：",

    "Start Rendering": "开始渲染",
    "Ready to Render": "准备渲染",
    "About FVisualizer": "关于本软件",
    "About": "关于",
    "Version: ": "版本：",
    "Support me if you like this application:": "如果你喜欢这个应用，欢迎来赞助我：",
    "About me:": "关于我：",
    "Special thanks to:": "特别感谢：",
    "... and all people who support me!": "……以及所有支持我的人！",

    "Output Path": "输出路径",
    "Select Path": "选择路径",
    "<Output Path>": "<输出路径>",
    "Untitled_Video": "未命名视频",

    "This folder is not exist!": "该文件夹不存在！",
    "Output folder is not exist!": "输出文件夹不存在！",
    "Sorry, this file is not supported!": "抱歉，该文件不受支持！",
    "Sorry, this audio file is not supported!": "抱歉，该音频文件不受支持！",

    "Yes": "是",
    "No": "否",
    "OK": "确定",

    "Rendering Aborted!": "渲染中断！",

    "_Visualize": "_音频可视化",
    "Output Path Selected: ": "已选择输出路径： ",
    "Font Selected: ": "已选择字体： ",
    "Cannot Render": "无法开始渲染",
    "Save Image as...": "图片另存为……",
    "Snap": "快照",
    "Cannot Save Image!": "无法储存图片！",

    "Please select the correct audio file!": "请先正确选择音频文件！",
    "Please select the correct output path!": "请正确选择输出路径！",
    "Please input the corrent file name!": "请正确输入输出文件名！",
    "Cannot open this image file!": "无法打开该图片！",
    "Stop Rendering...": "正在取消渲染……",

    "Audio (REQUIRED)": "声音文件【必选】",
    "Output (REQUIRED)": "输出路径【必选】",
    "Foreground Image": "选择主图片",
    "Background Image": "选择背景图片",
    "Logo File": "选择小图标",
    "Your Text:": "请输入文字：",
    "Font Size:": "字体大小：",
    "Text Brt.:": "文字亮度：",
    "Font File": "选择字体文件",
    "Video Size:": "视频尺寸：",
    "FPS:": "视频帧率：",
    "Render Quality:": "渲染质量：",
    "Video BR:": "视频码率：",
    "Auto Bit Rate": "自动视频码率",
    "Analyze Freq:": "频率分析范围：",
    "to": "至",
    "Hz": "赫兹",
    "Spectrum Num:": "频谱条的数量：",
    "Spectrum Scalar:": "频谱条灵敏倍率：",
    "Spec. Brt.:": "频谱亮度：",
    "Spec. Sat.:": "频谱饱和度：",
    "Spectrum Stabilize:": "频谱条防抖：",
    "Spec. Hue:": "频谱色调：",

    "Rainbow 4x": "彩虹 4x",
    "Rainbow 2x": "彩虹 2x",
    "Rainbow 1x": "彩虹 1x",
    "White": "白色",
    "Black": "黑色",
    "Gray": "灰色",
    "Red": "红色",
    "Green": "绿色",
    "Blue": "蓝色",
    "Yellow": "黄色",
    "Magenta": "品红",
    "Purple": "紫色",
    "Cyan": "青色",
    "Light Green": "浅绿",
    "Green - Blue": "渐变：蓝-绿",
    "Magenta - Purple": "渐变：红-紫",
    "Red - Yellow": "渐变：红-黄",
    "Yellow - Green": "渐变：黄-绿",
    "Blue - Purple": "渐变：蓝-紫",

    "Audio BR:": "音频码率：",
    "Normalize Volume": "标准化音量",
    "Frequency Analyzer Preset:": "频率分析预设：",
    "Pop Music": "流行音乐",
    "Classical Music": "古典音乐",
    "Calm Music": "舒缓音乐",
    "Orchestral Music": "管弦乐",
    "Piano: Narrow Band": "钢琴：窄频",
    "Piano: Wide Band": "钢琴：宽频",
    "Violin": "小提琴",
    "Guitar": "吉他",
    "Natural Sound": "自然音",
    "Voice": "语音",

    "Video Preset:": "视频预设：",
    "Square": "正方形",
    "Landscape": "横屏",
    "Portrait": "竖屏",
    "Very Low": "非常低",
    "Low": "低",
    "Medium - Default": "中等 - 默认",
    "High": "高",
    "Very High": "非常高",
    "Render Quality": "渲染品质",

    "(Slow)": "(缓慢)",
    "Preview": "预览",
    "Welcome to use": "欢迎使用",
    "-Please Select-": "-请选择-",
    "Notice": "通知",
    "Please stop rendering before quit!": "请在退出前取消渲染！",
    "Are you sure to overwrite this file?": "确定覆盖文件吗？",
    "Are you sure to stop rendering?": "确定取消渲染吗？",

    "Spectrum Style:": "频谱风格：",
    "Solid Line": "实线频谱",
    "Solid Line: Center": "实线频谱：居中",
    "Solid Line: Reverse": "实线频谱：反向",
    "Dot Line": "点线频谱",
    "Single Dot": "单点频谱",
    "Double Dot": "双点频谱",
    "Double Dot: Center": "双点频谱：居中",
    "Double Dot: Reverse": "双点频谱：反向",
    "Concentric": "同心圆",
    "Line Graph": "折线图",
    "Zooming Circles": "缩放圆形",
    "Classic Line: Center": "经典实线：中心",
    "Classic Line: Bottom": "经典实线：底部",
    "Classic Rectangle: Center": "经典长方形：中心",
    "Classic Rectangle: Bottom": "经典长方形：底部",
    "Classic Round Dot: Center": "经典圆点：中心",
    "Classic Round Dot: Bottom": "经典圆点：底部",
    "Classic Square Dot: Center": "经典方点：中心",
    "Classic Square Dot: Bottom": "经典方点：底部",
    "Stem Plot: Solid Single": "Stem图：单点实线",
    "Stem Plot: Solid Double": "Stem图：双点实线",
    "Stem Plot: Dashed Single": "Stem图：单点虚线",
    "Stem Plot: Dashed Double": "Stem图：双点虚线",
    "No Spectrum": "无频谱",

    "Line Width:": "频谱线宽：",
    "BG Mode:": "背景模式：",
    "Blurred BG Image": "模糊背景",
    "Normal BG Image": "正常背景",
    "Blurred BG Only": "仅模糊背景",
    "Normal BG Only": "仅正常背景",
    "Transparent": "透明背景",
    "Spectrum Only": "仅频谱",
    "Glow Text": "发光文字",
    "Glow Spec. (SLOW)": "发光频谱【缓慢】",
    "Project Website: ": "项目网站：",
    "Spin FG(rpm):": "旋转主图(转/分)：",
    "Oscillate Foreground": "振动主图",
    "Oscillate FG to Bass (%)": "随低音振动主图(%)",
    "Bass Frequency Range (%)": "低音频率范围(%)",

    "Error! Cannot save config!": "错误！不能保存配置！",
    "FFMPEG not found, please install FFMPEG!": "FFMPEG未安装，请安装FFMPEG！",

    "Adjust audio volume according to EBU R128 loudness standard.": "根据 EBU R128 标准调整音频的音量。",
    "Visualized spectrum will be generated according to this frequency range.": "软件将根据此频率范围绘制可视化频谱。",
    "Oscillate FG image accroding to the bass.": "根据低音振动主图",
    "Sensitivity of the bass (beat) detector.": "重低音（节拍）检测器的灵敏度。",
    "Relative frequency of bass to analyzer frequency range.": "重低音频率占分析器总频率的相对比例。",
}

lang_keys = list(lang_cn_s.keys())
lang_en = {}
for lang_key in lang_keys:
    lang_en[lang_key] = lang_key
